# TODO add all the logs to changes and sort changes.csv
import os

Ukrainian_Bible_Book_name_to_English_abbrevation = {
    "1 Мойсея": "GEN",
    "2 Мойсея": "EXO",
    "3 Мойсея": "LEV",
    "4 Мойсея": "NUM",
    "5 Мойсея": "DEU",
    "Иозея": "JOS",
    "Суддїв": "JDG",
    "Рути": "RUT",
    "1 Самуїлова": "1SA",
    "2 Самуїлова": "2SA",
    "1 Царів": "1KI",
    "2 Царів": "2KI",
    "1 Паралипоменон": "1CH",
    "2 Паралипоменон": "2CH",
    "Ездри": "EZR",
    "Неємії": "NEH",
    "Естери": "EST",
    "Йова": "JOB",
    "Псалтирь": "PSA",
    "Приповісток": "PRO",
    "Екклезіаста": "ECC",
    "Пісень": "SNG",
    "Ісаїї": "ISA",
    "Еремії": "JER",
    "Плач": "LAM",
    "Езекиїла": "EZK",
    "Даниїла": "DAN",
    "Осії": "HOS",
    "Йоіла": "JOL",
    "Амоса": "AMO",
    "Авдія": "OBA",
    "Йони": "JON",
    "Михея": "MIC",
    "Наума": "NAM",
    "Аввакума": "HAB",
    "Софонії": "ZEP",
    "Аггея": "HAG",
    "Захарії": "ZEC",
    "Малахія": "MAL",
    "Маттея": "MAT",
    "Марка": "MRK",
    "Луки": "LUK",
    "Йоана": "JHN",
    "Дїяння": "ACT",
    "Римлян": "ROM",
    "1 Коринтян": "1CO",
    "2 Коринтян": "2CO",
    "Галат": "GAL",
    "Єфесян": "EPH",
    "Филипян": "PHP",
    "Колосян": "COL",
    "1 Солунян": "1TH",
    "2 Солунян": "2TH",
    "1 Тимотея": "1TI",
    "2 Тимотея": "2TI",
    "Тита": "TIT",
    "Филимона": "PHM",
    "Жидів": "HEB",
    "Якова": "JAS",
    "1 Петра": "1PE",
    "2 Петра": "2PE",
    "1 Йоана": "1JN",
    "2 Йоана": "2JN",
    "3 Йоана": "3JN",
    "Юди": "JUD",
    "Одкриттє": "REV",
}
English_Bible_Book_abbreviations = (
    Ukrainian_Bible_Book_name_to_English_abbrevation.values()
)
print(English_Bible_Book_abbreviations)

root_folder = os.path.dirname(os.path.abspath(__file__))
target_path = os.path.join(root_folder, "..", "docs", "Checks", "Changes.csv")
with open(target_path, encoding="utf-8", mode="r") as f:
    lines = f.readlines()
